### ISSUE TITLE
[Feature] Card 컴포넌트

### ISSUE THREAD

**Issue by sungdongyoon** [Happi-Cat-Tiger/Happi-Day-Front#18]
## 🚩 이슈 요약
이벤트 / 굿즈 / 공구 카드 컴포넌트 구현
## 🚧 TO-DO
- [ ] 각 카드 타입 지정 (event / goods / sales)
- [ ] 타입 별 카드에 해당되는 데이터를 props로 전달하여 사용
## 🍀 추가 확인 사항
- [ ] 카드 이미지는 임시로 로고이미지 넣었습니다
- [ ] w:224px / h:300px로 우선 고정
- [ ] 수정사항 있으면 말씀해주세요!
