### ISSUE TITLE
[Feature] 이벤트 상세정보 페이지

### ISSUE THREAD

**Issue by sungdongyoon** [Happi-Cat-Tiger/Happi-Day-Front#50]
## 🚩 이슈 요약
이벤트 상세정보 페이지 레이아웃 작업
## 🚧 TO-DO
- [ ] 이벤트 id값을 통해 해당 이벤트 페이지로 이동
- [ ] 대략적인 레이아웃 작업
- [ ] 자세한 기능구현은 추후에 진행
